### ISSUE TITLE
Install guide

### ISSUE THREAD

**Issue by ChappIO** [nathanbreitsch/fuck-this-page#1]
Any way to deploy this in chrome? I'd like to have some fun with it :p

**Comment by nathanbreitsch** [comment]
Haha yeah!  There's a developer mode that you can use to test your own chrome extensions.  I'll see if I can pull up some instructions.  I doubt I can get this on the chrome store though, lol.

**Comment by nathanbreitsch** [comment]
Here are the instructions for adding an app using developer mode:
https://developer.chrome.com/extensions/getstarted#unpacked

This extension is pretty janky right now and works best on wikipedia.  Also, you have to disable the extension to stop it.  I didn't want to spend that much time on this project.  But if you can create a polished up webpage "profanitizer", I'd be interested in using/extending it.

**Comment by ChappIO** [comment]
Haha yea the store is probably a no-go. Unless you allow the user to pick the replacements :p

**Comment by ChappIO** [comment]
![image](https://cloud.githubusercontent.com/assets/13708940/13345798/f7e0424c-dc61-11e5-8220-56c886bbc6a1.png)

Seems to work ;) thanks mate. Keep making fun stuff like this haha.
